#### Ing. Jorge Eduardo Ronsón Ruiz
#### jerondonr@unal.edu.co - 3012751445
#### Universidad Nacional de Colombia

# **<center> Manipulación y algebra de tensores </center>**

# 1. Importar Librerias:

In [2]:
import tensorflow as tf
import numpy as np

# 2. Creación de un tensor

In [4]:
t0 = tf.constant(4)
print(t0) #Tensor de orden 0 (1 solo dato)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
t1 = tf.constant([1, 3, 4])
print(t1) #Tensor de orden 1 (vector)

tf.Tensor([1 3 4], shape=(3,), dtype=int32)


In [6]:
t23 = tf.constant([[1, 2, 3],[4, 5, 6]])
print(t23) #Tensor de orden 2 (matriz)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [7]:
t235 = tf.constant([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],
                    [[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]]])
print(t235) #Tensor de orden 3 (dos matrices)

tf.Tensor(
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]], shape=(2, 3, 5), dtype=int32)


In [9]:
t235.numpy() #Conversión del objeto tensor a un objeto de numpy. Ojo, no lo estoy guardando, apenas lo veo como
# array y luego vuelve a ser tensor

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]], dtype=int32)

In [10]:
t235.numpy().shape

(2, 3, 5)

In [11]:
t235.shape

TensorShape([2, 3, 5])

# 3. Algebra de tensores:

In [18]:
a = tf.constant([[1,2],[3,4]]) #Crea un tensor de orden 2
b = tf.constant([[5,6],[7,8]]) #Crea un tensor de orden 2

print(a,"\n")
print(b,"\n")
print(tf.add(a,b),"\n") #Realiza la suma punto a punto de los tensores a y b
print(tf.multiply(a,b),"\n") #Realiza la multiplicación punto a punto de los tensores a y b
print(tf.matmul(a,b),"\n") #Realiza la multiplicación de matrices de los tensores a y b

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32) 



In [20]:
print(a+b,"\n") #Realiza la misma operación que la función tf.add()
print(a*b, "\n") #Realiza la misma operación que la función tf.multiply()
print(a@b, "\n") #Realiza la misma operación que la función tf.matmul()

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32) 



# 4. Funciones de reducción

In [21]:
c = tf.constant([[4.0, 5.0],[10.0,1.0]]) #Crea un tensor de orden 2

print(c,"\n")
print(tf.reduce_max(c),"\n") #Me devuelve el máximo valor encontrado en el tensor.
print(tf.reduce_min(c),"\n") #Me devuelve el mínimo valor encontrado en el tensor.
print(tf.reduce_mean(c),"\n") #Me devuelve la media de los valores del tensor.
print(tf.argmax(c),"\n") # Me devuelve la posición del valor mas alto del tensor.
print(tf.nn.softmax(c),"\n") 
print(tf.reduce_sum(tf.nn.softmax(c),axis=1),"\n")

tf.Tensor(
[[ 4.  5.]
 [10.  1.]], shape=(2, 2), dtype=float32) 

tf.Tensor(10.0, shape=(), dtype=float32) 

tf.Tensor(1.0, shape=(), dtype=float32) 

tf.Tensor(5.0, shape=(), dtype=float32) 

tf.Tensor([1 0], shape=(2,), dtype=int64) 

tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32) 

tf.Tensor([1. 1.], shape=(2,), dtype=float32) 



# 5. Tipo, forma y dimensión

In [26]:
t = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],]) #Crea un tensor de orden 3
print(t.dtype,"\n") #Me devuelve el tipo de dato de los valores del tensor
print(t.shape,"\n") # Me devuelve la forma del tensor (cuantas columnas, filas, matrices, bloques de matrices, etc.)
print(t.ndim,"\n") # Me devuelve la dimensión del tensor.
print(t.shape[2],"\n") # Me devuelve la cantidad de elementos de la posición indicada: 2 matrices en este caso
print(tf.size(t.numpy()),"\n") # Me devuelve el tamaño del tensor.

<dtype: 'int32'> 

(3, 2, 5) 

3 

5 

tf.Tensor(30, shape=(), dtype=int32) 



# 6. Indexación

In [28]:
t1 =  tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print("Primero: ", t1[0]) # Me devuelve el valor que se encuentra en la posición 0
print("Segundo: ", t1[1]) # Me devuelve el valor que se encuentra en la posición 1
print("Ultimo: ", t1[-1].numpy()) # Me devuelve el valor que se encuentra en la ultima posición del tensor

Primero:  tf.Tensor(0, shape=(), dtype=int32)
Segundo:  tf.Tensor(1, shape=(), dtype=int32)
Ultimo:  34


In [32]:
print('Todo', t1[:].numpy()) # Me devuelve todos los valores del tensor.
print('Antes la posición 4 ', t1[:4].numpy()) # Me devuelve desde la ṕosición 0 hasta la 4-1
print('Desde la posición 4 hasta el final', t1[4:].numpy()) # Me devuelve los valores desde la posición 4 hasta la ultima
print('Desde la posición 2 hasta anterior a 7', t1[4:7].numpy()) #Me devuelve los valores desde la posición 4 hasta la 7-1
print('Todos los elementos en posición par ', t1[::2].numpy()) # Me devuelve todos los valores del tensor en pasos de 2 en 2
print('Invertido todo el orden', t1[::-1].numpy()) #Me devuelve todos los elementos del tensor pero de forma descendente

Todo [ 0  1  1  2  3  5  8 13 21 34]
Antes la posición 4  [0 1 1 2]
Desde la posición 4 hasta el final [ 3  5  8 13 21 34]
Desde la posición 2 hasta anterior a 7 [3 5 8]
Todos los elementos en posición par  [ 0  1  3  8 21]
Invertido todo el orden [34 21 13  8  5  3  2  1  1  0]


# 7. Indexación multieje

In [33]:
t23 = tf.constant([[1, 2, 3],[4, 5, 6]])
print(t23.numpy())

[[1 2 3]
 [4 5 6]]


In [35]:
print('Posición 1,1 = ',t23[1,1].numpy()) # Me devuelve el valor de la posición 1,1 (fila 1, columna 1)
print('Segunda fila: ', t23[1,:].numpy()) # Me devuelve todos los valores de la fila 1
print('Segunda columna: ', t23[:,1].numpy()) # Me devuelve todos los valores de la columna 1
print('Última columna: ', t23[:,-1].numpy()) # Me devuelve todos los valores de la ultima columna
print('Primer elemento de la última columna: ', t23[0,-1].numpy()) #Me devuelve la ultima columnna de la fila 0
print('Saltarse la primera columna: \n', t23[:,1:].numpy()) # Me devuelve todos los valores de las columnas desde la 1 hasta la ultima

Posición 1,1 =  5
Segunda fila:  [4 5 6]
Segunda columna:  [2 5]
Última columna:  [3 6]
Primer elemento de la última columna:  3
Saltarse la primera columna: 
 [[2 3]
 [5 6]]


In [36]:
t = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],]) 
print(t.numpy())

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [37]:
print('Extrae la primera capa\n', t[0,:,:]) #Me devuelve toda la primera matriz
print('Extrae la segunda capa\n', t[1]) #Me devuelve toda la segunda matriz

Extrae la primera capa
 tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)
Extrae la segunda capa
 tf.Tensor(
[[10 11 12 13 14]
 [15 16 17 18 19]], shape=(2, 5), dtype=int32)


# 8. Manipulación de forma:

In [38]:
x = tf.constant([[1],[2],[3]])
print(x.shape)
print(x.shape.as_list())

(3, 1)
[3, 1]


In [41]:
reshaped = tf.reshape(x,[1,3]) #Cambia la forma del tensor: pasa de tener 3 filas y 1 columna a tener 1 fila 3 columnas
# y se almacena en la variable reshaped.
print(reshaped.numpy())
print(x.numpy())

[[1 2 3]]
[[1]
 [2]
 [3]]


# 9. Aplanamiento del tensor:

In [43]:
print("t actual: \n", t.numpy())
flat = tf.reshape(t, [-1]) #Aplana el tensor, es decir, lo convierte en vector.
print("\n t aplanado: \n", flat.numpy())

t actual: 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]

 t aplanado: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [44]:
print(t.shape.as_list())

[3, 2, 5]


In [46]:
print(tf.reshape(t, [2*3,5])) #Modifica la forma del tensor en 2*3 filas y 5 columnas

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)


In [48]:
print(tf.reshape(t, [2,3*5])) #Modifica la forma del tensor en 2 filas y 3*5 columnas

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]], shape=(2, 15), dtype=int32)


In [53]:
print(tf.reshape(t, [-1,5])) # Modifica la forma del tensor en 5 columnas y el -1 le indica a python que 
# debe buscar la cantidad de filas que organizan completamente todos los datos de la forma original.

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)


In [54]:
print(tf.reshape(t, [3,-1])) #Igual que el caso anterior pero ahora ajusta las columnas.

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


In [55]:
print(tf.reshape(t, [3,2,5])) # Modifica la forma a 3 matrices de 2 filas y 5 columnas c/u.

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


# 9. Definición Conversión de tipos .cast

In [56]:
f64_tensor = tf.constant([2.0, 4.0, 6.0], dtype = tf.float64)
print(f64_tensor) # Crea un tensor cuyos tipos de datos se especifican como float64

f16_tensor = tf.cast(f64_tensor,dtype= tf.float16) #Se convierte el tipo de dato de los valores del tensor a float16
print(f16_tensor)

u8_tensor = tf.cast(f16_tensor, dtype = tf.uint8) # Se convierte a intero sin signo
print(u8_tensor)

tf.Tensor([2. 4. 6.], shape=(3,), dtype=float64)
tf.Tensor([2. 4. 6.], shape=(3,), dtype=float16)
tf.Tensor([2 4 6], shape=(3,), dtype=uint8)


# 10. Radiodifusión:
La radiodifusión es un concepto tomado de la función equivalente en NumPy . En resumen, bajo ciertas condiciones, los tensores más pequeños se "estiran" automáticamente para adaptarse a tensores más grandes cuando se ejecutan operaciones combinadas en ellos.

In [57]:
x = tf.constant([1, 2 ,3])
y = tf.constant(2)
z = tf.constant([2, 2 ,2])

# el mismo resultado
print(tf.multiply(x,2))
print(x*y) # El tensor y se convierte en un tensor de iguales dimensiones que el otro termino de la multiplicación
print(x*z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [60]:
x = tf.reshape(x, [3,1])
y = tf.range(1,5) #crea un vector con numeros enteros en pasos de 1 desde 1 hasta 5-1
print(x, "\n")
print(y, "\n")

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 



In [61]:
print(tf.multiply(x,y))

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [62]:
print(tf.broadcast_to([1,2,3], [3,3])) # Crea un tensor de 3 filas y 3 columnas con los valores de la lista.

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


# 11. Tensores irregulares:

In [63]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]
ragged_t = tf.ragged.constant(ragged_list)
print(ragged_t.shape) #Crea un tensor de 4 filas pero no define una cantidad de columnas.

(4, None)


# 12. Tensores de strings

In [65]:
st = tf.constant("Este tensor string")
print(st) # El prefijo b indica que el tipo (dtype)  tf.string no es unicode.

tf.Tensor(b'Este tensor string', shape=(), dtype=string)


In [66]:
print(tf.strings.split(st)) #Divide el tensor por palabras

tf.Tensor([b'Este' b'tensor' b'string'], shape=(3,), dtype=string)


In [68]:
st = tf.constant("1 10 10.4")

print(tf.strings.to_number(tf.strings.split(st, " ")))
# Imprime un tensor string convertido a numero identificando cada numero por que los separa un espacio " "

tf.Tensor([ 1.  10.  10.4], shape=(3,), dtype=float32)


# 13. Tensores dispersos

In [69]:
#  tensor disperso
sparse_tensor = tf.sparse.SparseTensor(indices = [[0,1], [1,2]],
                                       values = [1,2],
                                       dense_shape
                                        =[3,4])
print(sparse_tensor, "\n")

# convierte a tensor denso
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
